name: jikan
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/pastapareo/jikan-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.1
  oauth2: ^1.5.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  json_serializable: ^3.2.5
  pedantic: ^1.8.0
